ncservices/urls.py
from django.conf.urls import include
from allianceauth import urls
from django.urls import re_path, path

urlpatterns = [
    re_path(r"", include(urls)),
    path("__debug__/", include("debug_toolbar.urls")),
]

handler500 = "allianceauth.views.Generic500Redirect"
handler404 = "allianceauth.views.Generic404Redirect"
handler403 = "allianceauth.views.Generic403Redirect"
handler400 = "allianceauth.views.Generic400Redirect"

shipstats/urls.py
from django.urls import path

import shipstats.views

app_name = "shipstats"

urlpatterns = [
    path("", shipstats.views.index, name="index"),
    path(
        "reports/data/ship-stats/",
        shipstats.views.ship_stats_report_data,
        name="ship_stats_report_data",
    ),
    path(
        "reports/data/ship-stats/filters/",
        shipstats.views.ship_stats_filters,
        name="ship_stats_filters",
    ),
]

shipstats/views.py
import logging

from allianceauth.eveonline.models import EveCharacter
from django.http import JsonResponse
from django.shortcuts import render
from eveuniverse.models import EveRegion
from memberaudit.models import EveShipType, CharacterAsset

logger = logging.getLogger(__name__)


def index(request):

    return render(request, "shipstats/index.html")


def ship_stats_report_data(request):
    eve_ships = EveShipType.objects.all()
    ship_assets = CharacterAsset.objects.filter(eve_type__in=eve_ships).select_related(
        "location",
        "location__eve_solar_system",
        "location__eve_solar_system__eve_constellation",
        "location__eve_solar_system__eve_constellation__eve_region",
        "character__eve_character",
        "eve_type",
        "eve_type__eve_group",
    )

    data = []
    for asset in ship_assets:

        if (
            asset.location
            and asset.location.eve_solar_system
            and asset.location.eve_solar_system.eve_constellation
        ):
            region_name = (
                asset.location.eve_solar_system.eve_constellation.eve_region.name
            )
        else:
            region_name = ""

        asset_data = {
            "type": {
                "display": asset.eve_type.name,
                "sort": asset.eve_type.name,
            },
            "group": asset.eve_type.eve_group.name,
            "location": asset.location.name if asset.location else "",
            "region": region_name,
            "corporation_name": asset.character.eve_character.corporation_name,
            "character": asset.character.eve_character.character_name,
            "main": "foo",
        }
        data.append(asset_data)

    return JsonResponse({"data": data})


def ship_stats_filters(request):

    logger.info("Received request for ship stats filters: %s", request.GET)

    region_names = list(
        EveRegion.objects.all().order_by("name").values_list("name", flat=True)
    )

    ship_types = list(
        EveShipType.objects.all().order_by("name").values_list("name", flat=True)
    )

    ship_groups = list(
        set(
            EveShipType.objects.all()
            .order_by("eve_group__name")
            .values_list("eve_group__name", flat=True)
        )
    )

    corporation_names = list(
        EveCharacter.objects.values_list("corporation_name", flat=True).distinct()
    )

    filter_data = {
        "type": ship_types,
        "region": region_names,
        "group": sorted(ship_groups),
        "corporation_name": sorted(corporation_names),
    }

    return JsonResponse(filter_data)

shipstats/templates/shipstats/base.html
{% extends 'allianceauth/base.html' %}

{% block page_title %}
    {{ page_title|striptags }} - {{ app_title }}
{% endblock %}

{% block content %}
    <br />
    {% block details %}{% endblock %}
{% endblock %}

shipstats/templates/shipstats/index.html
{% extends 'shipstats/base.html' %}

{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}
    <div>
        {% include 'shipstats/partials/reports/tabs_navigation.html' %}

        <div class="panel panel-default panel-tabs">
            <div class="panel-body">
                <!-- Tab panes -->
                <div class="tab-content">
                    {% include 'shipstats/partials/reports/tabs/ship_stats.html' %}
                </div>
            </div>

        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}

    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/dataTables.rowGroup.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/filterDropDown.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#tab_ship_stats').DataTable({
                ajax: {
                    url: '{% url 'shipstats:ship_stats_report_data' %}',
                    dataSrc: 'data',
                    cache: false
                },
                columns: [
                    {
                        data: 'type',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'group' },
                    { data: 'location' },
                    { data: 'region' },
                    { data: 'corporation_name' },
                    { data: 'character' },
                    { data: 'main' },
                ],
                columnDefs: [],
                order: [ [ 0, "asc" ] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 0,
                            title: "{% translate 'Type' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 1,
                            title: "{% translate 'Group' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 3,
                            title: "{% translate 'Region' %}",
                            maxWidth: "12em"
                        },
                        {
                            idx: 4,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        }
                    ],
                    ajax:  '{% url 'shipstats:ship_stats_filters' %}',
                    bootstrap: true
                },
                createdRow: function( row, data, dataIndex )
                {
                    // if (data['is_compliant']){
                    //     $(row).addClass('success');
                    // }
                    // else if (data['is_registered']){
                    //     $(row).addClass('warning');
                    // }
                    // else {
                    //     $(row).addClass('danger');
                    // }
                }
            });

        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/reports.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}

{% endblock %}

shipstats/templates/shipstats/partials/reports/tabs/ship_stats.html
{% load i18n %}

<div role="tabpanel" class="tab-pane active" id="ship_stats">
    <div class="table-responsive">
        <table class="table table-striped table-width-fix" id="tab_ship_stats">
            <thead>
                <tr>
                    <th>{% translate 'Type' %}</th>
                    <th>{% translate 'Group' %}</th>
                    <th>{% translate 'Location' %}</th>
                    <th>{% translate 'Region' %}</th>
                    <th>{% translate 'Corporation' %}</th>
                    <th>{% translate 'Character' %}</th>
                    <th>{% translate 'Main' %}</th>
                </tr>
            </thead>

            <tbody></tbody>
        </table>
    </div>
    {% include 'memberaudit/partials/reports/tabs/_compliance_color_code.html' %}
</div>

shipstats/templates/shipstats/partials/reports/tabs_navigation.html
{% load i18n %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#shipstats" aria-controls="ship-stats" role="tab" data-toggle="tab">
            {% translate 'Ship Stats' %}
        </a>
    </li>
 </ul>